<Project Sdk="Microsoft.NET.Sdk">
    <!-- BepInEx properties. -->
    <PropertyGroup>
        <AssemblyName>itolib</AssemblyName>
        <Description>Wondrous gizmos and gadgets for the restless mind.</Description>
        <Version>0.8.1</Version>
    </PropertyGroup>

    <!-- Project properties. -->
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>preview</LangVersion>
        <PackageLicenseFile>../LICENSE</PackageLicenseFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <!-- Code linting. -->
    <PropertyGroup>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
        <AnalysisMode>All</AnalysisMode>
        <AnalysisLevel>preview-recommended</AnalysisLevel>
    </PropertyGroup>

    <!-- Embedded debug. -->
    <PropertyGroup>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>embedded</DebugType>
        <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=./</PathMap>
    </PropertyGroup>

    <!-- Enable 'Nullable' types. -->
    <PropertyGroup>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Unity.Analyzers" Version="1.*">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
        <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.*" PrivateAssets="all" />
        <PackageReference Include="BepInEx.BaseLib" Version="5.*" PrivateAssets="all" Publicize="true" />
        <PackageReference Include="BepInEx.Core" Version="5.*" PrivateAssets="all" />
        <PackageReference Include="UnityEngine.Modules" Version="2022.3.62" IncludeAssets="compile" PrivateAssets="all" />
        <PackageReference Include="LethalCompany.GameLibs.Steam" Version="73.0.0-ngd.0" PrivateAssets="all" Publicize="true" />
        <!-- <PackageReference Include="IAmBatby.LethalLevelLoader" Version="1.4.*" PrivateAssets="all" Publicize="true" /> -->

        <PackageReference Include="Evaisa.LethalLib" Version="1.1.*" PrivateAssets="all" />
        <PackageReference Include="TeamXiaolan.DawnLib" Version="0.8.*" PrivateAssets="all" />
        <PackageReference Include="mrov.WeatherRegistry" Version="0.8.*" PrivateAssets="all" />
        <PackageReference Include="mrov-WeatherTweaks" Version="1.1.*" PrivateAssets="all" />

        <PackageReference Include="CrowdControl-CrowdControl_LethalCompany" Version="1.1.*" PrivateAssets="all" Publicize="true" />
        <PackageReference Include="TeamXiaolan-FacilityMeltdown" Version="2.8.*" PrivateAssets="all" Publicize="true" />
        <PackageReference Include="BGN-PizzaTowerEscapeMusic" Version="2.4.*" PrivateAssets="all" Publicize="true" />
        <PackageReference Include="Rattenbonkers-TVLoader" Version="1.1.*" PrivateAssets="all" Publicize="true" />

        <Reference Include="LethalLevelLoader">
            <PrivateAssets>all</PrivateAssets>
            <Publicize>true</Publicize>
            <HintPath>managed\LethalLevelLoader.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <None Include="../LICENSE" Pack="true" PackagePath="$(PackageLicenseFile)" />
    </ItemGroup>

    <Target Name="NetcodePatch" AfterTargets="PostBuildEvent">
        <Exec Command="netcode-patch -uv 2022.3.62 -nv 1.12.0 -tv 1.0.0 &quot;$(TargetPath)&quot; @(ReferencePathWithRefAssemblies->'&quot;%(Identity)&quot;', ' ')" />
    </Target>

    <Target Name="PackThunderstore" AfterTargets="NetcodePatch">
        <Exec Command="dotnet tcli build --config-path &quot;../thunderstore.toml&quot; --package-version $(Version)" />
    </Target>
</Project>