using LethalLevelLoader;
using System;
using System.Security.Cryptography;
using System.Text;

namespace itolib.Interfaces
{
    /// <summary>
    ///     Adds seeded randomness capabilities to any implementing class, using the current round's map seed.
    /// </summary>
    /// <typeparam name="T">The seeded object itself, with which to generate a unique seed (derived from the map seed).</typeparam>
    /// <remarks>Handles automatically initializing a new, unique <c>Random</c> instance for each implementing class upon starting a new round.</remarks>
    public interface ISeededScript<T> where T : ISeededScript<T>
    {
        /// <summary>
        ///     Obtain a seeded <c>Random</c> instance initialized using a seed derived from the current map seed.
        /// </summary>
        static Random SeededRandom
        {
            get
            {
                if (StartOfRound.Instance != null && field == null)
                {
                    // Initialize a new Random instance using the current map seed and a specified (or generated) offset value.
                    field = new(StartOfRound.Instance.randomMapSeed + SeedOffset);

                    // Schedule seeded Random instance to be reset upon starting a new round.
                    LevelManager.GlobalLevelEvents.onLevelLoaded.AddListener(ResetRandom);
                }

                return (field) ?? new(); // Use a time-dependent seed as fallback, though this should never be the case.
            }
            private set;
        }

        /// <summary>
        ///     A set value to add to the current map seed, either specified or generated by hashing <c><typeparamref name="T"/></c>.
        /// </summary>
        static int SeedOffset
        {
            get
            {
                // Generate a seed offset, if one is not already set.
                _seedOffset ??= ComputeSeedOffset();

                return _seedOffset ?? 0;
            }
            set => _seedOffset = value;
        }
        private static int? _seedOffset;

        /// <summary>
        ///     Generate a unique integer for the implementing class, using a <c>SHA256</c> hash of <c><typeparamref name="T"/></c>'s name.
        /// </summary>
        /// <returns>The unique value to use as a seed offset for the implementing class' seeded <c>Random</c> instance.</returns>
        private static int ComputeSeedOffset()
        {
            byte[] hash = SHA256.Create().ComputeHash(Encoding.UTF8.GetBytes($"{typeof(T).Name}"));

            return BitConverter.ToInt32(hash, 0);
        }

        /// <summary>
        ///     Clear the implementing class' seeded <c>Random</c> instance, to generate a new one.
        /// </summary>
        private static void ResetRandom()
        {
            // Immediately unsubscribe from event.
            LevelManager.GlobalLevelEvents.onLevelLoaded.RemoveListener(ResetRandom);

            // Set Random instance back to null.
            SeededRandom = null!;
        }

        /// <summary>
        ///     Obtain a reference to the static seeded <c>Random</c> instance of the implementing class.
        /// </summary>
        /// <remarks>Intended to avoid having to call <c>ISeededScript &lt;<typeparamref name="T"/>&gt;.SeededRandom</c> statically.</remarks>
        /// <returns>The implementing class' seeded <c>Random</c> instance.</returns>
        Random GetSeededRandom()
        {
            return SeededRandom;
        }
    }
}