<Project Sdk="Microsoft.NET.Sdk">
    <!-- BepInEx properties. -->
    <PropertyGroup>
        <AssemblyName>itolib.editor</AssemblyName>
        <Description>Editor stuff for itolib.</Description>
        <Version>0.0.0</Version>
    </PropertyGroup>

    <!-- Project properties. -->
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>preview</LangVersion>
        <PackageLicenseFile>../LICENSE</PackageLicenseFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <!-- Code linting. -->
    <PropertyGroup>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
        <AnalysisMode>All</AnalysisMode>
        <AnalysisLevel>preview-recommended</AnalysisLevel>
    </PropertyGroup>

    <!-- Disable certain warnings. -->
    <PropertyGroup>
        <NoWarn>$(NoWarn);CA1000</NoWarn>
        <NoWarn>$(NoWarn);CA1051</NoWarn>
        <NoWarn>$(NoWarn);CA1707</NoWarn>
        <NoWarn>$(NoWarn);CA1859</NoWarn>
    </PropertyGroup>

    <!-- Embedded debug. -->
    <PropertyGroup>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>embedded</DebugType>
        <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=./</PathMap>
    </PropertyGroup>

    <!-- Enable 'Nullable' types. -->
    <PropertyGroup>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\itolib\itolib.csproj">
            <PrivateAssets>all</PrivateAssets>
            <Project>{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</Project>
            <Name>itolib</Name>
            <ReferenceOutputAssembly>true</ReferenceOutputAssembly>
        </ProjectReference>
        <PackageReference Include="Microsoft.Unity.Analyzers" Version="1.22.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
        <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.2" PrivateAssets="all" />
        <PackageReference Include="BepInEx.Core" Version="5.*" PrivateAssets="all" />
        <PackageReference Include="UnityEngine.Modules" Version="2022.3.62" IncludeAssets="compile" PrivateAssets="all" />

        <Reference Include="UnityEditor">
            <PrivateAssets>all</PrivateAssets>
            <HintPath>D:\Programs\Unity\2022.3.9f1\Editor\Data\Managed\UnityEditor.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine">
            <PrivateAssets>all</PrivateAssets>
            <HintPath>D:\Programs\Unity\2022.3.9f1\Editor\Data\Managed\UnityEngine.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <None Include="../LICENSE" Pack="true" PackagePath="$(PackageLicenseFile)" />
    </ItemGroup>
</Project>